name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build jaguar, panther, tiger
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: Goldfish64/MacPPCKernelSDK
          path: MacPPCKernelSDK

      - name: CI bootstrap prep
        uses: actions/checkout@v5
        with:
          repository: Wiintosh/powerpc-kext-ci
          token: ${{ secrets.POWERPC_KEXT_CI }}
          fetch-depth: 1
          lfs: true
          path: powerpc-kext-ci

      - name: CI bootstrap
        run: |
          cd powerpc-kext-ci
          ./install-darling.sh
          sudo darling shell ./install-xcode-tools.sh
          sudo apt install python3-lzss
          cd ..

      - name: Build drivers
        run: |
          make OSX_VERSION=jaguar && make package OSX_VERSION=jaguar
          make OSX_VERSION=panther && make package OSX_VERSION=panther
          make OSX_VERSION=tiger && make package OSX_VERSION=tiger

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: ./*.zip

      - name: Upload to Releases
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
